### ISSUE TITLE
用户管理

### ISSUE THREAD

**Issue by donghongtai** [52ABP/Documents#42]
用户管理

**Comment by donghongtai** [comment]
用户管理

**Comment by donghongtai** [comment]
用户管理.
本文作者：52ABP开发团队 
文章会随着版本进行更新，关注我们获取最新版本 
本文出处：https://www.52abp.com/wiki/52abp/latest 
源代码： https://www.github.com/52abp 

52ABP的项目中用户管理。

1. 用户管理
在52ABP主菜单选择【用户管理】



功能：
1.1 搜索
1.2 新增
1.3 删除
1.4 选择
1.5 批量删除
1.6 编辑
1.7 Excel导出



来文档中心了解更多：https://www.52abp.com/wiki/

微信关注我们不走丢

**Comment by donghongtai** [comment]
用户管理.
本文作者：52ABP开发团队
文章会随着版本进行更新，关注我们获取最新版本
本文出处：https://www.52abp.com/wiki/52abp/latest
源代码： https://www.github.com/52abp

52ABP的项目中用户管理。

用户管理
在52ABP主菜单   选择【管理】--【用户】
![image](https://user-images.githubusercontent.com/27189693/59246241-569d5500-8c4e-11e9-8830-887ebba1f351.png)

功能：

1 搜索
   在搜索框中输入要搜索的用户名称，按搜索的图标，就显示符合条件的用户。

2 添加用户
  ![image](https://user-images.githubusercontent.com/27189693/59246624-6c5f4a00-8c4f-11e9-91a6-351d1864dacf.png)
2.1 用户信息：
![image](https://user-images.githubusercontent.com/27189693/59247329-9580da00-8c51-11e9-9006-c7faf4489ac7.png)

    填写：用户名（必填项）、邮箱地址（必填项）、电话号码 、使用随机密码、是否启用了两个因素、下次登录需要修改密码、发送激活邮件、激活、启用锁定。
   上传：头像照片。

2.2 角色：
![image](https://user-images.githubusercontent.com/27189693/59247358-ad585e00-8c51-11e9-8e83-943ab4aceb22.png)

      选择 ：将该用户使用的角色勾选。

2.3 组织单元：
![image](https://user-images.githubusercontent.com/27189693/59247457-fad4cb00-8c51-11e9-8ec3-ce9395cc6329.png)

    在搜索框中输入要搜索的组织单元，按刷新图标，就显示符合条件的组织单元。
   选择：将该用户所属的组织单元勾选。

3 批量删除
![image](https://user-images.githubusercontent.com/27189693/59247773-05439480-8c53-11e9-812a-23d45f9a104b.png)

   对已勾选的用户批量删除。

4  Excel导出

   将显示的用户导出Excel表。

5 高级过滤
![image](https://user-images.githubusercontent.com/27189693/59248042-ceba4980-8c53-11e9-87af-2b20db8b9ff2.png)

  可以通过【权限过滤】和【角色过滤】来过滤用户。

6  修改
![image](https://user-images.githubusercontent.com/27189693/59248083-f9a49d80-8c53-11e9-9c3d-b561540b3967.png)

  可以通过用户信息【操作】项，按下【修改】，对用户的信息修改，内容同【添加用户】。

7. 删除
![image](https://user-images.githubusercontent.com/27189693/59248296-9404e100-8c54-11e9-97ef-646ba3d3c2d2.png)

  可以通过用户信息【操作】项，按下【删除】，对用户删除。 



来文档中心了解更多：https://www.52abp.com/wiki/

微信关注我们不走丢

**Comment by ltm0203** [comment]
已经验收。感谢。
