### ISSUE TITLE
功能介绍：角色管理

### ISSUE THREAD

**Issue by donghongtai** [52ABP/Documents#43]
角色管理

**Comment by donghongtai** [comment]
角色管理.
本文作者：52ABP开发团队
文章会随着版本进行更新，关注我们获取最新版本
本文出处：https://www.52abp.com/wiki/52abp/latest
源代码： https://www.github.com/52abp

52ABP的项目中角色管理。

角色管理
在52ABP主菜单 选择【管理】--【角色】

image
![image](https://user-images.githubusercontent.com/27189693/59315047-96197f00-8cea-11e9-8ca0-bca2ec4369f4.png)

功能：

1 搜索和权限过滤
 1.1 搜索
       在搜索框中输入要搜索的角色名称，按搜索的图标，就显示符合条件角色。
 1.2 权限过滤
![image](https://user-images.githubusercontent.com/27189693/59315165-2f489580-8ceb-11e9-8e34-e0cbd0e00fee.png)
  权限过滤是通过树形的权限列表，可以多选，见上图。
    
2 添加角色

2.1 角色名称：
 
![image](https://user-images.githubusercontent.com/27189693/59315275-a4b46600-8ceb-11e9-8795-ee900fe5336d.png)

填写：角色名称（必填项）。
选择：默认（是/否）

2.2 权限：
![image](https://user-images.githubusercontent.com/27189693/59315352-04127600-8cec-11e9-8583-cd65eb980c43.png)
选择：对该角色的权限进行勾选。
 
3 批量删除
 
对已勾选的角色批量删除。

4 修改
![image](https://user-images.githubusercontent.com/27189693/59315454-65d2e000-8cec-11e9-91b7-03ab98e00ea1.png)


可以通过用户信息【操作】项，按下【修改】，对角色的信息修改，内容同【添加角色】。

5 删除
![image](https://user-images.githubusercontent.com/27189693/59315520-a29ed700-8cec-11e9-8f37-211f70379775.png)

可以通过角色信息【操作】项，按下【删除】，对角色删除。
Admin是系统生成的角色，用户无法删除。

来文档中心了解更多：https://www.52abp.com/wiki/

微信关注我们不走丢

**Comment by ltm0203** [comment]
@donghongtai 感谢。

已经验收。

下次建议通过提交文件的形式来提交信息。
比如这篇的地址是

文件地址：https://github.com/52ABP/Documents/blob/dev-mvc-book/docs/Features-52ABP-NG-Role-Management.md
