### ISSUE TITLE
功能介绍：组织单元

### ISSUE THREAD

**Issue by donghongtai** [52ABP/Documents#44]
组织单元
本文作者：52ABP开发团队
文章会随着版本进行更新，关注我们获取最新版本
本文出处：https://www.52abp.com/wiki/52abp/latest
源代码： https://www.github.com/52abp

52ABP的项目中组织单元。

组织单元
在52ABP主菜单 选择【管理】--【组织单元】
 
![image](https://user-images.githubusercontent.com/27189693/59315790-d8908b00-8ced-11e9-945b-ecb859a05582.png)

功能：

1 组织结构树
1.1 新组织单元

![image](https://user-images.githubusercontent.com/27189693/59315844-1ab9cc80-8cee-11e9-8d4e-03a6229cc601.png)

 填写：组织单元（必填项）。
 

2.2 组织单元维护：

![image](https://user-images.githubusercontent.com/27189693/59315920-76845580-8cee-11e9-86ef-b6e01ef0313b.png)

选择组织单元，按右键，出现维护菜单。

2.2.1 修改

![image](https://user-images.githubusercontent.com/27189693/59316014-ebf02600-8cee-11e9-9564-d486ad4c30ca.png)

 内容同【新组织单元】。
 
2.2.2 添加下级组织

![image](https://user-images.githubusercontent.com/27189693/59316064-2ce83a80-8cef-11e9-8270-03fda50cebce.png)

 内容同【新组织单元】。

2.2.3  删除

![image](https://user-images.githubusercontent.com/27189693/59316121-6caf2200-8cef-11e9-8d44-d29a14f585af.png)

  按【删除】，系统有提示框【确定要删除吗？】。

3 添加用户
选择左边的组织结构树中的组织单元，可以对该组织单元添加用户。

![image](https://user-images.githubusercontent.com/27189693/59316312-63728500-8cf0-11e9-8f48-fa53d4706da9.png)

3.1 可以搜索符合条件的用户。
3.2 勾选需要添加的用户。

4 批量删除

![image](https://user-images.githubusercontent.com/27189693/59316406-ee537f80-8cf0-11e9-8b3d-d9789d4bbaa9.png)

可以批量删除该组织单元的用户列表中选中的用户。

5 删除
![image](https://user-images.githubusercontent.com/27189693/59316675-3de67b00-8cf2-11e9-9066-2ab317fc6075.png)

 该组织单元的用户列表【操作】的【删除】功能，可以将选择的用户从该组织单元的删除。

来文档中心了解更多：https://www.52abp.com/wiki/

微信关注我们不走丢

**Comment by ltm0203** [comment]
已经验收，Thanks♪(･ω･)ﾉ。
