### ISSUE TITLE
EF CORE集成 各个数据库的文章翻译

### ISSUE THREAD

**Issue by ltm0203** [52ABP/Documents#8]
https://github.com/52ABP/Documents/blob/master/ABP%E6%A1%86%E6%9E%B6%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3/EF-Core-MySql-Integration.md

https://github.com/52ABP/Documents/blob/master/ABP%E6%A1%86%E6%9E%B6%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3/EF-Core-PostgreSql-Integration.md

以上为路径信息。
@livisun 麻烦抽空翻译下

**Comment by livisun** [comment]
收到，我尽量保证翻译准确

> [https://github.com/52ABP/Documents/blob/master/ABP%E6%A1%86%E6%9E%B6%E4%B8%AD%E6%96%87%E6%96%87%E6% A1％A3 / EF-Core-MySql-Integration.md](https://github.com/52ABP/Documents/blob/master/ABP%E6%A1%86%E6%9E%B6%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3/EF-Core-MySql-Integration.md)
> 
> [https://github.com/52ABP/Documents/blob/master/ABP%E6%A1%86%E6%9E%B6%E4%B8%AD%E6%96%87%E6%96%87%E6% A1％A3 / EF-Core-PostgreSql-Integration.md](https://github.com/52ABP/Documents/blob/master/ABP%E6%A1%86%E6%9E%B6%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3/EF-Core-PostgreSql-Integration.md)
> 
> 以上为路径信息。
> @ livisun麻烦抽空翻译下

收到，尽量保证翻译质量

**Comment by ltm0203** [comment]
ok，已经处理。
以后翻译的时候，文件名称 不要进行修改，否则到时候会和 生成的目录无法对应上。
